Numpy provides support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate

In [2]:
import numpy as np

Creating 1d array

In [3]:
arr1 = np.array([1,2,3,4,5])

In [4]:
print(arr1)

[1 2 3 4 5]


In [5]:
print(type(arr1))

<class 'numpy.ndarray'>


In [9]:
print(arr1.shape)  #single dimension will show blank after comma

(5,)


In [ ]:
arr1.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [8]:
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

2d array

In [13]:
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [14]:
print(arr3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])