Numpy provides support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate

In [1]:
import numpy as np

Creating 1d array

In [3]:
arr1 = np.array([1,2,3,4,5])

In [4]:
print(arr1)

[1 2 3 4 5]


In [5]:
print(type(arr1))

<class 'numpy.ndarray'>


In [9]:
print(arr1.shape)  #single dimension will show blank after comma

(5,)


In [ ]:
arr1.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [8]:
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

2d array

In [13]:
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [14]:
print(arr3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Identity matrix: All diagonal elements will be 1 rest 0

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
print(arr3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [23]:
arr3.ndim

2

In [24]:
arr3.dtype

dtype('int64')

In [25]:
arr3.itemsize

8

Numpy Vectorized Operation

In [26]:
array1 = np.array([1,2,3,4,5,11,23])
array2 = np.array([3,4,5,6,7,3,1])

In [27]:
array1+array2

array([ 4,  6,  8, 10, 12, 14, 24])

In [28]:
array1 * array2

array([ 3,  8, 15, 24, 35, 33, 23])

Universal function

In [29]:
np.sqrt(array1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       3.31662479, 4.79583152])

In [30]:
np.exp(array1)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 5.98741417e+04, 9.74480345e+09])

In [31]:
np.sin(array1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.99999021, -0.8462204 ])

In [32]:
np.log(array1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       2.39789527, 3.13549422])

Array slicing and indexing

In [33]:
my_array = np.array([[1,2,3,4,4],[5,6,7,8,9],[11,22,55,33,76]])
print(my_array)

[[ 1  2  3  4  4]
 [ 5  6  7  8  9]
 [11 22 55 33 76]]


In [34]:
my_array[0]

array([1, 2, 3, 4, 4])

In [38]:
my_array[0][2]

np.int64(3)

In [36]:
print(my_array[0][2])

3


In [37]:
my_array[2]

array([11, 22, 55, 33, 76])

In [39]:
print(my_array[2][1])

22


In [40]:
my_array[1:]

array([[ 5,  6,  7,  8,  9],
       [11, 22, 55, 33, 76]])

In [41]:
my_array[1:,2:]

array([[ 7,  8,  9],
       [55, 33, 76]])

In [42]:
my_array[::-1]

array([[11, 22, 55, 33, 76],
       [ 5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  4]])

In [55]:
my_array[0:2,2:]

array([[3, 4, 4],
       [7, 8, 9]])

In [72]:
my_array[1:,1:3]

array([[ 6,  7],
       [22, 55]])

In [73]:
my_array[1:3,1:3]

array([[ 6,  7],
       [22, 55]])

In [74]:
my_array[0,0] = 100
print(my_array)

[[100   2   3   4   4]
 [  5   6   7   8   9]
 [ 11  22  55  33  76]]


Practical application: Normalization

In [75]:
#Calculating mean and standard deviation
data = np.array([10,34,53,56,32])

mean = np.mean(data)
std = np.std(data)

normalized_data = data - mean / std
print(normalized_data)

[ 7.77286172 31.77286172 50.77286172 53.77286172 29.77286172]


In [76]:
mean = np.mean(data)
print(f"Mean: {mean}")

median = np.median(data)
print(f"Median: {median}")

variance = np.var(data)
print(f"Variance: {variance}")

Mean: 37.0
Median: 34.0
Variance: 276.0


In [78]:
#Logical operation
data > 20

array([False,  True,  True,  True,  True])

In [89]:
data<30

array([ True, False, False, False, False])

In [90]:
data[data<30]

array([10])

In [88]:
print(data[(data>=20) & (data<40)])

[34 32]


In [2]:
data2 = np.array([[1,2,3,4],[5,4,2,4],[3,2,3,4]])
data2

array([[1, 2, 3, 4],
       [5, 4, 2, 4],
       [3, 2, 3, 4]])

In [7]:
data2[0]

array([1, 2, 3, 4])

In [14]:
data2[0:2,1:3]

array([[2, 3],
       [4, 2]])

In [16]:
data2[1:2,0:3]

array([[5, 4, 2]])

In [3]:
data2[2:3]

array([[3, 2, 3, 4]])