Numpy provides support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate

In [2]:
import numpy as np

Creating 1d array

In [3]:
arr1 = np.array([1,2,3,4,5])

In [4]:
print(arr1)

[1 2 3 4 5]


In [5]:
print(type(arr1))

<class 'numpy.ndarray'>


In [9]:
print(arr1.shape)  #single dimension will show blank after comma

(5,)


In [ ]:
arr1.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [8]:
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

2d array

In [13]:
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [14]:
print(arr3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Identity matrix: All diagonal elements will be 1 rest 0

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
print(arr3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [23]:
arr3.ndim

2

In [24]:
arr3.dtype

dtype('int64')

In [25]:
arr3.itemsize

8

Numpy Vectorized Operation

In [26]:
array1 = np.array([1,2,3,4,5,11,23])
array2 = np.array([3,4,5,6,7,3,1])

In [27]:
array1+array2

array([ 4,  6,  8, 10, 12, 14, 24])

In [28]:
array1 * array2

array([ 3,  8, 15, 24, 35, 33, 23])

Universal function

In [29]:
np.sqrt(array1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       3.31662479, 4.79583152])

In [30]:
np.exp(array1)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 5.98741417e+04, 9.74480345e+09])

In [31]:
np.sin(array1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.99999021, -0.8462204 ])

In [32]:
np.log(array1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       2.39789527, 3.13549422])

Array slicing and indexing

In [33]:
my_array = np.array([[1,2,3,4,4],[5,6,7,8,9],[11,22,55,33,76]])
print(my_array)

[[ 1  2  3  4  4]
 [ 5  6  7  8  9]
 [11 22 55 33 76]]


In [34]:
my_array[0]

array([1, 2, 3, 4, 4])

In [38]:
my_array[0][2]

np.int64(3)

In [36]:
print(my_array[0][2])

3


In [37]:
my_array[2]

array([11, 22, 55, 33, 76])

In [39]:
print(my_array[2][1])

22
